// Generated by scripts/generate-otel-proto.mjs. Do not edit.
export const otelProtoSchema = {
  "nested": {
    "opentelemetry": {
      "nested": {
        "proto": {
          "nested": {
            "collector": {
              "nested": {
                "trace": {
                  "nested": {
                    "v1": {
                      "nested": {
                        "ExportTracePartialSuccess": {
                          "fields": {
                            "errorMessage": {
                              "id": 2,
                              "protoName": "error_message",
                              "type": "string"
                            },
                            "rejectedSpans": {
                              "id": 1,
                              "protoName": "rejected_spans",
                              "type": "int64"
                            }
                          }
                        },
                        "ExportTraceServiceRequest": {
                          "fields": {
                            "resourceSpans": {
                              "id": 1,
                              "protoName": "resource_spans",
                              "rule": "repeated",
                              "type": "opentelemetry.proto.trace.v1.ResourceSpans"
                            }
                          }
                        },
                        "ExportTraceServiceResponse": {
                          "fields": {
                            "partialSuccess": {
                              "id": 1,
                              "protoName": "partial_success",
                              "type": "ExportTracePartialSuccess"
                            }
                          }
                        },
                        "TraceService": {
                          "methods": {
                            "Export": {
                              "requestType": "ExportTraceServiceRequest",
                              "responseType": "ExportTraceServiceResponse"
                            }
                          }
                        }
                      },
                      "options": {
                        "csharp_namespace": "OpenTelemetry.Proto.Collector.Trace.V1",
                        "go_package": "go.opentelemetry.io/proto/otlp/collector/trace/v1",
                        "java_multiple_files": true,
                        "java_outer_classname": "TraceServiceProto",
                        "java_package": "io.opentelemetry.proto.collector.trace.v1"
                      }
                    }
                  }
                }
              }
            },
            "common": {
              "nested": {
                "v1": {
                  "nested": {
                    "AnyValue": {
                      "fields": {
                        "arrayValue": {
                          "id": 5,
                          "protoName": "array_value",
                          "type": "ArrayValue"
                        },
                        "boolValue": {
                          "id": 2,
                          "protoName": "bool_value",
                          "type": "bool"
                        },
                        "bytesValue": {
                          "id": 7,
                          "protoName": "bytes_value",
                          "type": "bytes"
                        },
                        "doubleValue": {
                          "id": 4,
                          "protoName": "double_value",
                          "type": "double"
                        },
                        "intValue": {
                          "id": 3,
                          "protoName": "int_value",
                          "type": "int64"
                        },
                        "kvlistValue": {
                          "id": 6,
                          "protoName": "kvlist_value",
                          "type": "KeyValueList"
                        },
                        "stringValue": {
                          "id": 1,
                          "protoName": "string_value",
                          "type": "string"
                        },
                        "stringValueStrindex": {
                          "id": 8,
                          "protoName": "string_value_strindex",
                          "type": "int32"
                        }
                      },
                      "oneofs": {
                        "value": {
                          "oneof": [
                            "stringValue",
                            "boolValue",
                            "intValue",
                            "doubleValue",
                            "arrayValue",
                            "kvlistValue",
                            "bytesValue",
                            "stringValueStrindex"
                          ]
                        }
                      }
                    },
                    "ArrayValue": {
                      "fields": {
                        "values": {
                          "id": 1,
                          "rule": "repeated",
                          "type": "AnyValue"
                        }
                      }
                    },
                    "EntityRef": {
                      "fields": {
                        "descriptionKeys": {
                          "id": 4,
                          "protoName": "description_keys",
                          "rule": "repeated",
                          "type": "string"
                        },
                        "idKeys": {
                          "id": 3,
                          "protoName": "id_keys",
                          "rule": "repeated",
                          "type": "string"
                        },
                        "schemaUrl": {
                          "id": 1,
                          "protoName": "schema_url",
                          "type": "string"
                        },
                        "type": {
                          "id": 2,
                          "type": "string"
                        }
                      }
                    },
                    "InstrumentationScope": {
                      "fields": {
                        "attributes": {
                          "id": 3,
                          "rule": "repeated",
                          "type": "KeyValue"
                        },
                        "droppedAttributesCount": {
                          "id": 4,
                          "protoName": "dropped_attributes_count",
                          "type": "uint32"
                        },
                        "name": {
                          "id": 1,
                          "type": "string"
                        },
                        "version": {
                          "id": 2,
                          "type": "string"
                        }
                      }
                    },
                    "KeyValue": {
                      "fields": {
                        "key": {
                          "id": 1,
                          "type": "string"
                        },
                        "keyStrindex": {
                          "id": 3,
                          "protoName": "key_strindex",
                          "type": "int32"
                        },
                        "value": {
                          "id": 2,
                          "type": "AnyValue"
                        }
                      }
                    },
                    "KeyValueList": {
                      "fields": {
                        "values": {
                          "id": 1,
                          "rule": "repeated",
                          "type": "KeyValue"
                        }
                      }
                    }
                  },
                  "options": {
                    "csharp_namespace": "OpenTelemetry.Proto.Common.V1",
                    "go_package": "go.opentelemetry.io/proto/otlp/common/v1",
                    "java_multiple_files": true,
                    "java_outer_classname": "CommonProto",
                    "java_package": "io.opentelemetry.proto.common.v1"
                  }
                }
              }
            },
            "resource": {
              "nested": {
                "v1": {
                  "nested": {
                    "Resource": {
                      "fields": {
                        "attributes": {
                          "id": 1,
                          "rule": "repeated",
                          "type": "opentelemetry.proto.common.v1.KeyValue"
                        },
                        "droppedAttributesCount": {
                          "id": 2,
                          "protoName": "dropped_attributes_count",
                          "type": "uint32"
                        },
                        "entityRefs": {
                          "id": 3,
                          "protoName": "entity_refs",
                          "rule": "repeated",
                          "type": "opentelemetry.proto.common.v1.EntityRef"
                        }
                      }
                    }
                  },
                  "options": {
                    "csharp_namespace": "OpenTelemetry.Proto.Resource.V1",
                    "go_package": "go.opentelemetry.io/proto/otlp/resource/v1",
                    "java_multiple_files": true,
                    "java_outer_classname": "ResourceProto",
                    "java_package": "io.opentelemetry.proto.resource.v1"
                  }
                }
              }
            },
            "trace": {
              "nested": {
                "v1": {
                  "nested": {
                    "ResourceSpans": {
                      "fields": {
                        "resource": {
                          "id": 1,
                          "type": "opentelemetry.proto.resource.v1.Resource"
                        },
                        "schemaUrl": {
                          "id": 3,
                          "protoName": "schema_url",
                          "type": "string"
                        },
                        "scopeSpans": {
                          "id": 2,
                          "protoName": "scope_spans",
                          "rule": "repeated",
                          "type": "ScopeSpans"
                        }
                      },
                      "reserved": [
                        [
                          1000,
                          1000
                        ]
                      ]
                    },
                    "ScopeSpans": {
                      "fields": {
                        "schemaUrl": {
                          "id": 3,
                          "protoName": "schema_url",
                          "type": "string"
                        },
                        "scope": {
                          "id": 1,
                          "type": "opentelemetry.proto.common.v1.InstrumentationScope"
                        },
                        "spans": {
                          "id": 2,
                          "rule": "repeated",
                          "type": "Span"
                        }
                      }
                    },
                    "Span": {
                      "fields": {
                        "attributes": {
                          "id": 9,
                          "rule": "repeated",
                          "type": "opentelemetry.proto.common.v1.KeyValue"
                        },
                        "droppedAttributesCount": {
                          "id": 10,
                          "protoName": "dropped_attributes_count",
                          "type": "uint32"
                        },
                        "droppedEventsCount": {
                          "id": 12,
                          "protoName": "dropped_events_count",
                          "type": "uint32"
                        },
                        "droppedLinksCount": {
                          "id": 14,
                          "protoName": "dropped_links_count",
                          "type": "uint32"
                        },
                        "endTimeUnixNano": {
                          "id": 8,
                          "protoName": "end_time_unix_nano",
                          "type": "fixed64"
                        },
                        "events": {
                          "id": 11,
                          "rule": "repeated",
                          "type": "Event"
                        },
                        "flags": {
                          "id": 16,
                          "type": "fixed32"
                        },
                        "kind": {
                          "id": 6,
                          "type": "SpanKind"
                        },
                        "links": {
                          "id": 13,
                          "rule": "repeated",
                          "type": "Link"
                        },
                        "name": {
                          "id": 5,
                          "type": "string"
                        },
                        "parentSpanId": {
                          "id": 4,
                          "protoName": "parent_span_id",
                          "type": "bytes"
                        },
                        "spanId": {
                          "id": 2,
                          "protoName": "span_id",
                          "type": "bytes"
                        },
                        "startTimeUnixNano": {
                          "id": 7,
                          "protoName": "start_time_unix_nano",
                          "type": "fixed64"
                        },
                        "status": {
                          "id": 15,
                          "type": "Status"
                        },
                        "traceId": {
                          "id": 1,
                          "protoName": "trace_id",
                          "type": "bytes"
                        },
                        "traceState": {
                          "id": 3,
                          "protoName": "trace_state",
                          "type": "string"
                        }
                      },
                      "nested": {
                        "Event": {
                          "fields": {
                            "attributes": {
                              "id": 3,
                              "rule": "repeated",
                              "type": "opentelemetry.proto.common.v1.KeyValue"
                            },
                            "droppedAttributesCount": {
                              "id": 4,
                              "protoName": "dropped_attributes_count",
                              "type": "uint32"
                            },
                            "name": {
                              "id": 2,
                              "type": "string"
                            },
                            "timeUnixNano": {
                              "id": 1,
                              "protoName": "time_unix_nano",
                              "type": "fixed64"
                            }
                          }
                        },
                        "Link": {
                          "fields": {
                            "attributes": {
                              "id": 4,
                              "rule": "repeated",
                              "type": "opentelemetry.proto.common.v1.KeyValue"
                            },
                            "droppedAttributesCount": {
                              "id": 5,
                              "protoName": "dropped_attributes_count",
                              "type": "uint32"
                            },
                            "flags": {
                              "id": 6,
                              "type": "fixed32"
                            },
                            "spanId": {
                              "id": 2,
                              "protoName": "span_id",
                              "type": "bytes"
                            },
                            "traceId": {
                              "id": 1,
                              "protoName": "trace_id",
                              "type": "bytes"
                            },
                            "traceState": {
                              "id": 3,
                              "protoName": "trace_state",
                              "type": "string"
                            }
                          }
                        },
                        "SpanKind": {
                          "values": {
                            "SPAN_KIND_CLIENT": 3,
                            "SPAN_KIND_CONSUMER": 5,
                            "SPAN_KIND_INTERNAL": 1,
                            "SPAN_KIND_PRODUCER": 4,
                            "SPAN_KIND_SERVER": 2,
                            "SPAN_KIND_UNSPECIFIED": 0
                          }
                        }
                      }
                    },
                    "SpanFlags": {
                      "values": {
                        "SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK": 256,
                        "SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK": 512,
                        "SPAN_FLAGS_DO_NOT_USE": 0,
                        "SPAN_FLAGS_TRACE_FLAGS_MASK": 255
                      }
                    },
                    "Status": {
                      "fields": {
                        "code": {
                          "id": 3,
                          "type": "StatusCode"
                        },
                        "message": {
                          "id": 2,
                          "type": "string"
                        }
                      },
                      "nested": {
                        "StatusCode": {
                          "values": {
                            "STATUS_CODE_ERROR": 2,
                            "STATUS_CODE_OK": 1,
                            "STATUS_CODE_UNSET": 0
                          }
                        }
                      },
                      "reserved": [
                        [
                          1,
                          1
                        ]
                      ]
                    },
                    "TracesData": {
                      "fields": {
                        "resourceSpans": {
                          "id": 1,
                          "protoName": "resource_spans",
                          "rule": "repeated",
                          "type": "ResourceSpans"
                        }
                      }
                    }
                  },
                  "options": {
                    "csharp_namespace": "OpenTelemetry.Proto.Trace.V1",
                    "go_package": "go.opentelemetry.io/proto/otlp/trace/v1",
                    "java_multiple_files": true,
                    "java_outer_classname": "TraceProto",
                    "java_package": "io.opentelemetry.proto.trace.v1"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
} as const;
